services:
  db:
    image: pgvector/pgvector:pg16
    container_name: devmemory_ai_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devmemory_ai
    ports:
      - "5432:5432"
    volumes:
      - devmemory_ai_data:/var/lib/postgresql/data

volumes:
  devmemory_ai_data:
